In [1]:
# test connect
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [2]:
mushroom = pd.read_csv('mushrooms.csv')
mushroom.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
print(np.shape(mushroom))

(8124, 23)


In [6]:
mushroom.dropna()
print(np.shape(mushroom))

(8124, 23)


In [7]:
y=mushroom['class']
x=mushroom.drop('class',axis=1)
print(y.head())
print(x.head())

0    p
1    e
2    e
3    p
4    e
Name: class, dtype: object
  cap-shape cap-surface cap-color bruises odor gill-attachment gill-spacing  \
0         x           s         n       t    p               f            c   
1         x           s         y       t    a               f            c   
2         b           s         w       t    l               f            c   
3         x           y         w       t    p               f            c   
4         x           s         g       f    n               f            w   

  gill-size gill-color stalk-shape  ... stalk-surface-below-ring  \
0         n          k           e  ...                        s   
1         b          k           e  ...                        s   
2         b          n           e  ...                        s   
3         n          n           e  ...                        s   
4         b          k           t  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-t

In [25]:
mushroom.describe()

class    cap-shape  cap-surface    cap-color      bruises  \
count  8124.000000  8124.000000  8124.000000  8124.000000  8124.000000   
mean      0.482029     3.348104     1.827671     4.504677     0.415559   
std       0.499708     1.604329     1.229873     2.545821     0.492848   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     2.000000     0.000000     3.000000     0.000000   
50%       0.000000     3.000000     2.000000     4.000000     0.000000   
75%       1.000000     5.000000     3.000000     8.000000     1.000000   
max       1.000000     5.000000     3.000000     9.000000     1.000000   

              odor  gill-attachment  gill-spacing    gill-size   gill-color  \
count  8124.000000      8124.000000   8124.000000  8124.000000  8124.000000   
mean      4.144756         0.974151      0.161497     0.309207     4.810684   
std       2.103729         0.158695      0.368011     0.462195     3.540359   
min       0.000000         0.000000      0.000000     0.000000     0.000000   
25%       2.000000         1.000000      0.000000     0.000000     2.000000   
50%       5.000000         1.000000      0.000000     0.000000     5.000000   
75%       5.000000         1.000000      0.000000     1.000000     7.000000   
max       8.000000         1.000000      1.000000     1.000000    11.000000   

       ...  stalk-surface-below-ring  stalk-color-above-ring  \
count  ...               8124.000000             8124.000000   
mean   ...                  1.603644                5.816347   
std    ...                  0.675974                1.901747   
min    ...                  0.000000                0.000000   
25%    ...                  1.000000                6.000000   
50%    ...                  2.000000                7.000000   
75%    ...                  2.000000                7.000000   
max    ...                  3.000000                8.000000   

       stalk-color-below-ring  veil-type   veil-color  ring-number  \
count             8124.000000     8124.0  8124.000000  8124.000000   
mean                 5.794682        0.0     1.965534     1.069424   
std                  1.907291        0.0     0.242669     0.271064   
min                  0.000000        0.0     0.000000     0.000000   
25%                  6.000000        0.0     2.000000     1.000000   
50%                  7.000000        0.0     2.000000     1.000000   
75%                  7.000000        0.0     2.000000     1.000000   
max                  8.000000        0.0     3.000000     2.000000   

         ring-type  spore-print-color   population      habitat  
count  8124.000000        8124.000000  8124.000000  8124.000000  
mean      2.291974           3.596750     3.644018     1.508616  
std       1.801672           2.382663     1.252082     1.719975  
min       0.000000           0.000000     0.000000     0.000000  
25%       0.000000           2.000000     3.000000     0.000000  
50%       2.000000           3.000000     4.000000     1.000000  
75%       4.000000           7.000000     4.000000     2.000000  
max       4.000000           8.000000     5.000000     6.000000  

[8 rows x 23 columns]

### 2.1.3 Naive Bayes Classifier

In [40]:
# split the data for gaussian naive bayes classifier
# GaussianNB implements the Gaussian Naive Bayes algorithm for classification. The likelihood of the features is assumed to be Gaussian
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=404)
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [41]:
# Use confusion matrix for result analysis
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
y_pred_nb_train=nb.predict(x_train)
y_pred_nb_test=nb.predict(x_test)
print(confusion_matrix(y_train,y_pred_nb_train))
print(confusion_matrix(y_test,y_pred_nb_test))

[[2906  247]
 [ 231 2709]]
[[960  95]
 [ 71 905]]


In [42]:
# Use classification report to get general evaluation metrics
print(classification_report(y_train,y_pred_nb_train))
print(classification_report(y_test,y_pred_nb_test))

              precision    recall  f1-score   support

           0       0.93      0.92      0.92      3153
           1       0.92      0.92      0.92      2940

    accuracy                           0.92      6093
   macro avg       0.92      0.92      0.92      6093
weighted avg       0.92      0.92      0.92      6093

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      1055
           1       0.91      0.93      0.92       976

    accuracy                           0.92      2031
   macro avg       0.92      0.92      0.92      2031
weighted avg       0.92      0.92      0.92      2031



In [43]:
# accuracy of using naive bayes classifier
print(accuracy_score(y_train,y_pred_nb_train))
print(accuracy_score(y_test,y_pred_nb_test))

0.9215493188905302
0.9182668636139832


### 2.1.4 SVC Classifier

In [44]:
from sklearn.svm import SVC
svc_linear=SVC(kernel='linear')
svc_linear.fit(x_train,y_train)
svc_sigmoid=SVC(kernel='sigmoid')
svc_sigmoid.fit(x_train,y_train)
svc_poly=SVC(kernel='poly')
svc_poly.fit(x_train,y_train)
svc_rbf=SVC(kernel='rbf')
svc_rbf.fit(x_train,y_train)

C:\Users\Wenyu\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Wenyu\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Wenyu\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [45]:
y_pred_sigmoid=svc_sigmoid.predict(x_test)
y_pred_linear=svc_linear.predict(x_test)
y_pred_poly=svc_poly.predict(x_test)
y_pred_rbf=svc_rbf.predict(x_test)

In [46]:
print(confusion_matrix(y_test,y_pred_sigmoid))
print(confusion_matrix(y_test,y_pred_linear))
print(confusion_matrix(y_test,y_pred_poly))
print(confusion_matrix(y_test,y_pred_rbf))

[[1055    0]
 [ 976    0]]
[[1015   40]
 [  40  936]]
[[1055    0]
 [   0  976]]
[[1055    0]
 [   0  976]]


In [47]:
print(classification_report(y_test,y_pred_sigmoid))
print(classification_report(y_test,y_pred_linear))
print(classification_report(y_test,y_pred_poly))
print(classification_report(y_test,y_pred_rbf))

              precision    recall  f1-score   support

           0       0.52      1.00      0.68      1055
           1       0.00      0.00      0.00       976

    accuracy                           0.52      2031
   macro avg       0.26      0.50      0.34      2031
weighted avg       0.27      0.52      0.36      2031

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1055
           1       0.96      0.96      0.96       976

    accuracy                           0.96      2031
   macro avg       0.96      0.96      0.96      2031
weighted avg       0.96      0.96      0.96      2031

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1055
           1       1.00      1.00      1.00       976

    accuracy                           1.00      2031
   macro avg       1.00      1.00      1.00      2031
weighted avg       1.00      1.00      1.00      2031

              preci

C:\Users\Wenyu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [39]:
print(round(accuracy_score(y_test,y_pred_sigmoid),2))
print(round(accuracy_score(y_test,y_pred_linear),2))
print(accuracy_score(y_test,y_pred_poly))
print(accuracy_score(y_test,y_pred_rbf))

0.52


0.96


1.0


1.0
